title: Floating little leaves of code
email: silverhammermba@gmail.com
baseurl: "/blog"
url: "https://silverhammermba.github.io"
github_username:  silverhammermba

# Build settings
markdown: kramdown
