title: Floating little leaves of code
baseurl: "/blog"
author: Maxwell Anselm
description: A blog is a regularly updated website or web page, typically one run by an individual or small group, that is written in an informal or conversational style.
url: "https://silverhammermba.github.io"
github_username:  silverhammermba
permalink: /:year/:month/:day/:title
disqus:
  shortname: floatinglittleleavesofcode

# Build settings
markdown: kramdown
theme: minima
plugins:
    - jekyll-feed
